apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fsjs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0025-tenant/ci10t-777-0025-app/devfile-sample-fsjs@sha256:b5345758c2b9313333eaef5909398b46ac4d5a85579d047eacf96f02fa2856d3
        name: my-nodejs
        resources: {}
status: {}
