apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fsjs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fsjs
    app.kubernetes.io/part-of: ci10t-777-0025-app
  name: devfile-sample-fsjs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fsjs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fsjs
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0025-tenant/ci10t-777-0025-app/devfile-sample-fsjs@sha256:b5345758c2b9313333eaef5909398b46ac4d5a85579d047eacf96f02fa2856d3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
